eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  
microservice:
 payment-service:
   enpoints:
     enpoint:
       uri: http://PAYMENT-SERVICE/payment/doPayment
 order-service:
   enpoints:
     enpoint:
       uri: http://ORDER-SERVICE/order/bookOrder    
